### ISSUE TITLE
Fatal error on page load on server

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/kvsun.com#147]
```
TypeError: Argument 1 passed to KVSun\KVSAPI\Home::_getImage() must be of the type integer, string given, called in /var/www/html/kvsun.com/classes/kvsun/kvsapi/home.php on line 122 and defined in /var/www/html/kvsun.com/classes/kvsun/kvsapi/traits/images.php:14
Stack trace:
#0 /var/www/html/kvsun.com/classes/kvsun/kvsapi/home.php(122): KVSun\KVSAPI\Home->_getImage('https://kernval...')
#1 [internal function]: KVSun\KVSAPI\Home->_reduceSections(Object(stdClass), Object(stdClass))
#2 /var/www/html/kvsun.com/classes/kvsun/kvsapi/home.php(84): array_reduce(Array, Array, Object(stdClass))
#3 /var/www/html/kvsun.com/classes/kvsun/kvsapi/abstracts/content.php(32): KVSun\KVSAPI\Home->_setData(Object(shgysk8zer0\Core\PDOStatement))
#4 /var/www/html/kvsun.com/classes/kvsun/kvsapi/home.php(42): KVSun\KVSAPI\Abstracts\Content->_init(Object(shgysk8zer0\Core\PDO), 'https://dev2.kv...')
#5 /var/www/html/kvsun.com/functions.php(1295): KVSun\KVSAPI\Home->__construct(Object(shgysk8zer0\Core\PDO), 'https://dev2.kv...', Array)
#6 [internal function]: KVSun\Functions\load_file('head')
#7 /var/www/html/kvsun.com/functions.php(1276): array_map('KVSun\\Functions...', Array)
#8 /var/www/html/kvsun.com/functions.php(60): KVSun\Functions\load('head', 'header', 'nav', 'main', 'sidebar', 'footer')
#9 /var/www/html/kvsun.com/index.php(18): KVSun\Functions\build_dom(Array)
#10 {main}
```

**Comment by shgysk8zer0** [comment]
This was only due to importing an outdated database version.

Wish that there was a better way of dealing with that.
